---
SMSCs:
  - Name: smsc-cluster01-vs
    IP: 192.168.1.1
    Port: 2775
    BindPassword: passwd1
    BindSystemID: smsc-1-1
  - Name: smsc-cluster-02-vs
    IP: 192.168.1.2
    Port: 2775
    BindPassword: passwd2
    BindSystemID: smsc-2-1